version: '3.2'

services:

  mariadb-encrypted:
    container_name: mariadb-encrypted
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: espocrm
      MYSQL_PASSWORD: '1'
      MYSQL_ROOT_PASSWORD: '1'
      MYSQL_USER: espocrm
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mariadb-encrypted/keys/keyfile.key:/etc/mysql/encryption/keyfile.key
      - ./mariadb-encrypted/keys/keyfile.enc:/etc/mysql/encryption/keyfile.enc
      - ./mariadb-encrypted/data:/var/lib/mysql
      - ./mariadb-encrypted/logs:/var/log/mysql
    command:
      - --max-allowed-packet=100M
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --net-write-timeout=300
      - --net-read-timeout=300
      - --log-error=/var/log/mysql/mysql-error.log
      - --plugin-load-add=file_key_management
      - --file-key-management-filename=/etc/mysql/encryption/keyfile.enc
      - --file-key-management-filekey=FILE:/etc/mysql/encryption/keyfile.key
      - --file-key-management-encryption-algorithm=AES_CTR
      - --innodb-encrypt-log=ON
      - --innodb-encrypt-tables=FORCE

  php7.4:
    container_name: php7.4
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
     - ./html:/var/www/html
     - ./logs/apache2:/var/log/apache2
    restart: unless-stopped
    ports:
      - 8080:80
