version: '3'

networks:
  external_network:
    external: true
  internal_network:
    external: false
    internal: true

services:

  espocrm-mysql:
    container_name: espocrm-mysql
    image: mysql:latest # or mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - internal_network

  espocrm-php:
    container_name: espocrm-php
    hostname: "espocrm-php"
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:cached
      - ./logs/php-fpm:/var/log/php-fpm
    restart: unless-stopped
    depends_on:
      - espocrm-mysql
    networks:
      - internal_network
      - external_network

  espocrm-nginx:
    container_name: espocrm-nginx
    hostname: "espocrm-nginx"
    image: nginx
    volumes:
      - ./html:/var/www/html
      #- ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./nginx/espocrm.conf:/etc/nginx/espocrm.conf
      - ./logs/nginx:/var/log/nginx
    restart: unless-stopped
    depends_on:
      - espocrm-php
    ports:
      - 8080:80
    networks:
      - internal_network
      - external_network
